version: "0.0.1"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: SysadminsDecide.
    ports:
      - "5002:5432"