services: 
  api:
    build: 
      context: .
      dockerfile: ./${ASPNETCORE_ENVIRONMENT}/Dockerfile
    ports:
      - "5000:80"
    networks: 
      - wordcount
    depends_on: 
      - db
    environment: 
      - database_host=${db_host}
      - database_username=${db_username}
      - database_database=${POSTGRES_DATABASE}
      - database_password=${POSTGRES_PASSWORD}
      - database_port=${db_port}
      - database_connectionString=${db_connectionString}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    volumes:
      - .:/app
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - "5002:5432"
    networks: 
      - wordcount
    volumes:
      - dbvolume:/var/lib/postgresql/data

networks:
  wordcount:
    driver: bridge
volumes:
  dbvolume:
    driver: local