services: 
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks: 
      - wordcount
    depends_on: 
      - db
    environment: 
      - database:host=${db_host}
      - database:username=${db_username}
      - database:database=${POSTGRES_DATABASE}
      - database:password=${POSTGRES_PASSWORD}
      - database:port=${db_port}
      - database:connectionString=${db_connectionString}
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - "5002:5432"
    networks: 
      - wordcount
    volumes:
      - dbvolume:/var/lib/postgresql/data

networks:
  wordcount:
    driver: bridge
volumes: 
  dbvolume:
    driver: local