services: 
  api:
    build: 
      context: .
      dockerfile: ./${ASPNETCORE_ENVIRONMENT}/Dockerfile
    ports:
      - "5000:80"
    networks: 
      - wordcount
    depends_on: 
      - db
    environment: 
      - db_host=${db_host}
      - db_username=${db_username}
      - db_database=${db_database}
      - db_password=${db_password}
      - db_port=${db_port}
      - db_schema=${db_schema}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
    volumes:
      - .:/app
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${db_password}
      - POSTGRES_DATABASE=${db_database}
    ports:
      - "5002:5432"
    networks:
      - wordcount
    volumes:
      - dbvolume:/var/lib/postgresql/data
networks:
  wordcount:
    driver: bridge
volumes:
  dbvolume:
    driver: local