version: 0.0.1
services: 
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks: 
      - wordcount
    depends_on: 
      - db
    environment:
      - database:host=db
      - database:username=postgres
      - database:password=Sysadmins.
      - database:database=wordcount
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Sysadmins.
      - POSTGRES_DATABASE=wordcount
    ports:
      - "5002:5432"
    networks: 
      - wordcount
networks:
  wordcount:
    driver: bridge