// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WordCount.Data;

namespace WordCount.Migrations
{
    [DbContext(typeof(ArticleContext))]
    [Migration("20211022125909_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Code_first_test.Models.Article", b =>
                {
                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<long?>("Name")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("TotalWordsInArticle")
                        .HasColumnType("integer");

                    b.HasKey("ArticleId");

                    b.HasIndex("Name");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Code_first_test.Models.OccursIn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long?>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<int>("Occurances")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("WordOccurances");
                });

            modelBuilder.Entity("Code_first_test.Models.Publisher", b =>
                {
                    b.Property<long>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("PublisherId");

                    b.ToTable("Publishers");
                });

            modelBuilder.Entity("Code_first_test.Models.Word", b =>
                {
                    b.Property<string>("Literal")
                        .HasColumnType("text");

                    b.HasKey("Literal");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("OccursInWord", b =>
                {
                    b.Property<long>("OccursInId")
                        .HasColumnType("bigint");

                    b.Property<string>("WordsLiteral")
                        .HasColumnType("text");

                    b.HasKey("OccursInId", "WordsLiteral");

                    b.HasIndex("WordsLiteral");

                    b.ToTable("OccursInWord");
                });

            modelBuilder.Entity("Code_first_test.Models.Article", b =>
                {
                    b.HasOne("Code_first_test.Models.Publisher", null)
                        .WithMany("Articles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Code_first_test.Models.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("Name");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Code_first_test.Models.OccursIn", b =>
                {
                    b.HasOne("Code_first_test.Models.Article", "Article")
                        .WithMany("ContainedWords")
                        .HasForeignKey("ArticleId");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("OccursInWord", b =>
                {
                    b.HasOne("Code_first_test.Models.OccursIn", null)
                        .WithMany()
                        .HasForeignKey("OccursInId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Code_first_test.Models.Word", null)
                        .WithMany()
                        .HasForeignKey("WordsLiteral")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Code_first_test.Models.Article", b =>
                {
                    b.Navigation("ContainedWords");
                });

            modelBuilder.Entity("Code_first_test.Models.Publisher", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
