CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "JsonSchema" (
    "SchemaName" text NOT NULL,
    "JsonString" jsonb NOT NULL,
    CONSTRAINT "PK_JsonSchema" PRIMARY KEY ("SchemaName")
);

CREATE TABLE "Publisher" (
    "PublisherName" text NOT NULL,
    CONSTRAINT "PK_Publisher" PRIMARY KEY ("PublisherName")
);

CREATE TABLE "Words" (
    "Literal" text NOT NULL,
    CONSTRAINT "PK_Words" PRIMARY KEY ("Literal")
);

CREATE TABLE "Article" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "FilePath" text NOT NULL,
    "Title" text NOT NULL,
    "TotalWords" integer NOT NULL,
    "PublisherName" text NOT NULL,
    CONSTRAINT "PK_Article" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Article_Publisher_PublisherName" FOREIGN KEY ("PublisherName") REFERENCES "Publisher" ("PublisherName") ON DELETE CASCADE
);

CREATE TABLE "WordOccurrence" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ArticleId" bigint NOT NULL,
    "WordLiteral" text NULL,
    "Count" integer NOT NULL,
    CONSTRAINT "PK_WordOccurrence" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WordOccurrence_Article_ArticleId" FOREIGN KEY ("ArticleId") REFERENCES "Article" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WordOccurrence_Words_WordLiteral" FOREIGN KEY ("WordLiteral") REFERENCES "Words" ("Literal")
);

CREATE INDEX "IX_Article_PublisherName" ON "Article" ("PublisherName");

CREATE UNIQUE INDEX "IX_Publisher_PublisherName" ON "Publisher" ("PublisherName");

CREATE INDEX "IX_WordOccurrence_ArticleId" ON "WordOccurrence" ("ArticleId");

CREATE INDEX "IX_WordOccurrence_WordLiteral" ON "WordOccurrence" ("WordLiteral");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211201100149_NewModels', '6.0.0');

COMMIT;
