CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE json_schema (
    schema_name text NOT NULL,
    json_binary jsonb NULL,
    CONSTRAINT "PK_json_schema" PRIMARY KEY (schema_name)
);

CREATE TABLE "Publishers" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "SourceName" text NULL,
    CONSTRAINT "PK_Publishers" PRIMARY KEY ("Id")
);

CREATE TABLE wordratios (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    wordname citext NULL,
    amount integer NOT NULL,
    articletitle text NULL,
    filepath text NULL,
    totalwordsinarticle integer NOT NULL,
    sourceid bigint NOT NULL,
    sourcename varchar NULL,
    percent numeric(38,17) NOT NULL,
    fid bigint NOT NULL,
    CONSTRAINT "PK_wordratios" PRIMARY KEY (id)
);
